[package]
name = "noise_did_vc"
version = "0.1.0"
edition = "2021"

[dependencies]
snow = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"
async-std = "1.10"
did-key = "0.1.1"
ucan = { version = "0.7.0-alpha.1" }